apiVersion: v1
kind: Secret
metadata:
  name: btcpay-secrets
  namespace: btcpay
type: Opaque
stringData:
  BTCPAY_POSTGRES_PASSWORD: change-me-set-in-btcpay-env
  BTC_RPC_PASSWORD: change-me-set-in-btcpay-env
  BTC_RPC_USER: btcpay_rpc
