apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: veritas

resources:
  - ../../base

images:
  - name: localhost:31500/auth-svc
    newName: ghcr.io/jpg19/veritasvpn/auth-svc
    newTag: latest
  - name: localhost:31500/wg-manager
    newName: ghcr.io/jpg19/veritasvpn/wg-manager
    newTag: latest
  - name: localhost:31500/billing-svc
    newName: ghcr.io/jpg19/veritasvpn/billing-svc
    newTag: latest
  - name: localhost:31500/veritas-agent
    newName: ghcr.io/jpg19/veritasvpn/veritas-agent
    newTag: latest
  - name: localhost:31500/veritas-proxy
    newName: ghcr.io/jpg19/veritasvpn/veritas-proxy
    newTag: latest

patches:
  - target:
      kind: ConfigMap
      name: veritas-config
    patch: |-
      - op: replace
        path: /data/ENVIRONMENT
        value: "production"
      - op: replace
        path: /data/LOG_LEVEL
        value: "info"
      - op: replace
        path: /data/ALLOW_MOCK_BTCPAY
        value: "false"

  - target:
      kind: Deployment
      name: redis
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
